/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package siuv;

/**
 *
 * @author Sayli
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnInven = new javax.swing.JButton();
        btnCP = new javax.swing.JButton();
        btnVent = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnCC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btnClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CLI1.png"))); // NOI18N
        btnClientes.setOpaque(false);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes);
        btnClientes.setBounds(110, 140, 180, 140);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIUV - Sistema de Apoyo de Decisiones");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 50, 460, 40);

        btnInven.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/INV1.png"))); // NOI18N
        btnInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvenActionPerformed(evt);
            }
        });
        getContentPane().add(btnInven);
        btnInven.setBounds(110, 320, 180, 140);

        btnCP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CPP1.png"))); // NOI18N
        btnCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPActionPerformed(evt);
            }
        });
        getContentPane().add(btnCP);
        btnCP.setBounds(320, 140, 180, 140);

        btnVent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VEN1.png"))); // NOI18N
        btnVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentActionPerformed(evt);
            }
        });
        getContentPane().add(btnVent);
        btnVent.setBounds(530, 140, 180, 140);

        btnProveedores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PRO1.png"))); // NOI18N
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnProveedores);
        btnProveedores.setBounds(530, 320, 180, 140);

        btnCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CPC1.png"))); // NOI18N
        btnCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCCActionPerformed(evt);
            }
        });
        getContentPane().add(btnCC);
        btnCC.setBounds(320, 320, 180, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoGris.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 820, 500);

        setSize(new java.awt.Dimension(831, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        Clientes.Clientes client = new Clientes.Clientes();
        client.setAlwaysOnTop(true);
        client.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvenActionPerformed
        // TODO add your handling code here:
         Inventarios.JFrameInicio inven = new Inventarios.JFrameInicio();
        inven.setAlwaysOnTop(true);
        inven.setVisible(true);
    }//GEN-LAST:event_btnInvenActionPerformed

    private void btnCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPActionPerformed
        // TODO add your handling code here:
          CPP.CPPInicio cuentasP = new CPP.CPPInicio();
        cuentasP.setAlwaysOnTop(true);
        cuentasP.setVisible(true);
        
    }//GEN-LAST:event_btnCPActionPerformed

    private void btnVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentActionPerformed
        // TODO add your handling code here:
        
        Ventas.PrincipalVentas vent = new Ventas.PrincipalVentas();
        vent.setAlwaysOnTop(true);
        vent.setVisible(true);
    }//GEN-LAST:event_btnVentActionPerformed

    private void btnCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCCActionPerformed
        // TODO add your handling code here:
       CPC.CPCLogin cpc = new CPC.CPCLogin();
        cpc.setAlwaysOnTop(true);
        cpc.setVisible(true);
        
    }//GEN-LAST:event_btnCCActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
        
         Proveedores.Menu_proveedores provee = new Proveedores.Menu_proveedores();
        provee.setAlwaysOnTop(true);
        provee.setVisible(true);
        
    }//GEN-LAST:event_btnProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCC;
    private javax.swing.JButton btnCP;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnInven;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnVent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
