/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siuv;

import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.io.*;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.*;
import net.sf.jasperreports.view.*;

/**
 *
 * @author Sayli
 */
public class reportViewer extends javax.swing.JInternalFrame {

    Connection conn;
    MysqlDataSource ds = new MysqlDataSource();
    
    /**
     * Creates new form reportViewer
     * @param filename
     * @param parametro
     */
    public reportViewer(String filename, HashMap parametro){
        super("Reportes");
        initComponents();
        ds.setUser("root");
        ds.setPassword("1234");
        ds.setDatabaseName("siuv");
        ds.setServerName("127.0.0.1");
        try{
            conn = ds.getConnection();
            JasperPrint print = JasperFillManager.fillReport(filename, parametro, conn);
            JRViewer viewer = new JRViewer(print);
        
            Container c = getContentPane();
            c.setLayout(new BorderLayout());
            c.add(viewer);
        }
        catch(JRException ex){
        
        } catch (SQLException ex) {
            Logger.getLogger(reportViewer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
