/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CPP;

import java.awt.Dimension;


/**
 *
 * @author lscauv
 */
public class CPPInicio extends javax.swing.JFrame {

    /**
     * Creates new form CPCInicio
     */
    public CPPInicio() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Pagos = new java.awt.Button();
        button2 = new java.awt.Button();
        button1 = new java.awt.Button();
        button5 = new java.awt.Button();
        btnSalir = new java.awt.Button();
        lblNombre1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Pagos1 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button6 = new java.awt.Button();
        btnSalir1 = new java.awt.Button();
        escritorio = new javax.swing.JDesktopPane();
        lblNombre3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Pagos2 = new java.awt.Button();
        PagosProveedor = new java.awt.Button();
        btnSalir3 = new java.awt.Button();
        PagosAcreedor = new java.awt.Button();
        menuBar = new javax.swing.JMenuBar();
        menuReportes = new javax.swing.JMenu();
        NuevoAcreedor = new javax.swing.JMenuItem();
        NuevoPago = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        reportePagosPeriodoMenu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombre.setText("Cuentas por Pagar: ");

        jLabel1.setText("Seleccione la opcion:");

        Pagos.setActionCommand("button2");
        Pagos.setLabel("Pagos");

        button2.setLabel("Pagos pendientes");

        button1.setActionCommand("button3");
        button1.setLabel("Consulta");

        button5.setActionCommand("button4");
        button5.setLabel("Generar reporte");
        button5.setName(""); // NOI18N

        btnSalir.setLabel("Salir");
        btnSalir.setName("Cancelar"); // NOI18N

        lblNombre1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombre1.setText("Cuentas por Pagar: ");

        jLabel2.setText("Seleccione la opcion:");

        Pagos1.setActionCommand("button2");
        Pagos1.setLabel("Pagos");

        button3.setLabel("Pagos pendientes");

        button4.setActionCommand("button3");
        button4.setLabel("Consulta");

        button6.setActionCommand("button4");
        button6.setLabel("Generar reporte");
        button6.setName(""); // NOI18N

        btnSalir1.setLabel("Salir");
        btnSalir1.setName("Cancelar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Módulo de cuentas por cobrar");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(450, 350));
        getContentPane().setLayout(null);

        lblNombre3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblNombre3.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre3.setText("Cuentas por Pagar: ");
        lblNombre3.setBounds(410, 90, 450, 60);
        escritorio.add(lblNombre3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seleccione la opcion:");
        jLabel4.setBounds(530, 260, 220, 50);
        escritorio.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Pagos2.setActionCommand("button2");
        Pagos2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Pagos2.setLabel("Pagos");
        Pagos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pagos2ActionPerformed(evt);
            }
        });
        Pagos2.setBounds(120, 380, 230, 70);
        escritorio.add(Pagos2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PagosProveedor.setActionCommand("button3");
        PagosProveedor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PagosProveedor.setLabel("Consulta Proveedor");
        PagosProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagosProveedorActionPerformed(evt);
            }
        });
        PagosProveedor.setBounds(630, 380, 260, 70);
        escritorio.add(PagosProveedor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnSalir3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalir3.setLabel("Salir");
        btnSalir3.setName("Cancelar"); // NOI18N
        btnSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir3ActionPerformed(evt);
            }
        });
        btnSalir3.setBounds(930, 380, 250, 70);
        escritorio.add(btnSalir3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PagosAcreedor.setActionCommand("button3");
        PagosAcreedor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PagosAcreedor.setLabel("Consulta Acreedor");
        PagosAcreedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagosAcreedorActionPerformed(evt);
            }
        });
        PagosAcreedor.setBounds(380, 380, 210, 70);
        escritorio.add(PagosAcreedor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(escritorio);
        escritorio.setBounds(0, 0, 1370, 750);

        menuReportes.setText("Archivo");

        NuevoAcreedor.setText("Nuevo Acreedor");
        NuevoAcreedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoAcreedorActionPerformed(evt);
            }
        });
        menuReportes.add(NuevoAcreedor);

        NuevoPago.setText("Nuevo Pago");
        NuevoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoPagoActionPerformed(evt);
            }
        });
        menuReportes.add(NuevoPago);
        menuReportes.add(jSeparator2);

        reportePagosPeriodoMenu.setText("Reporte de pagos por período");
        reportePagosPeriodoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportePagosPeriodoMenuActionPerformed(evt);
            }
        });
        menuReportes.add(reportePagosPeriodoMenu);
        menuReportes.add(jSeparator3);

        menuBar.add(menuReportes);

        jMenu1.setText("Opciones");
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pagos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pagos2ActionPerformed
        // TODO add your handling code here:
        Pagos obj = new Pagos();
        escritorio.add(obj);
        obj.show();
        
    }//GEN-LAST:event_Pagos2ActionPerformed

    private void btnSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalir3ActionPerformed

    private void PagosAcreedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagosAcreedorActionPerformed
        PagosPendientesAcreedor obj = new PagosPendientesAcreedor();
        escritorio.add(obj);
        obj.show();        
    }//GEN-LAST:event_PagosAcreedorActionPerformed

    private void NuevoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoPagoActionPerformed
        Pagos obj = new Pagos();
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_NuevoPagoActionPerformed

    private void NuevoAcreedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoAcreedorActionPerformed
        Acreedor obj = new Acreedor();
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_NuevoAcreedorActionPerformed

    private void PagosProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagosProveedorActionPerformed
        PagosPendientesProveedor obj = new PagosPendientesProveedor();
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_PagosProveedorActionPerformed

    private void reportePagosPeriodoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportePagosPeriodoMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportePagosPeriodoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPPInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPPInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPPInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPPInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CPPInicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem NuevoAcreedor;
    private javax.swing.JMenuItem NuevoPago;
    private java.awt.Button Pagos;
    private java.awt.Button Pagos1;
    private java.awt.Button Pagos2;
    private java.awt.Button PagosAcreedor;
    private java.awt.Button PagosProveedor;
    private java.awt.Button btnSalir;
    private java.awt.Button btnSalir1;
    private java.awt.Button btnSalir3;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem reportePagosPeriodoMenu;
    // End of variables declaration//GEN-END:variables
}
