/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CPP;

import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sayli
 */
public class PagosAcreedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form cobroUnico
     */
    String f = "";
    Connection conexion;
    ResultSet rs;
    PreparedStatement psExecute;
    Statement stmt;
    MysqlDataSource data = new MysqlDataSource();
    String nombre;
    
    public PagosAcreedores() {
        initComponents();
    }
    
    public PagosAcreedores(String factura){
        initComponents();
        f = factura;
        conseguirFactura(f);
    }
    
    private void conseguirFactura(String fact){
        data.setUser("root");
        data.setPassword("1234");
        data.setDatabaseName("siuv");
        data.setServerName("127.0.0.1");
        
        try
        {
            conexion = data.getConnection();
            psExecute = conexion.prepareStatement("SELECT v.ID_NFacturas as 'ID', c.Razon_social as 'Nombre', v.ID_Producto as 'ID_Prod', p.Descripcion as 'Producto', v.Cant_producto as 'Cantidad', v.Sub_total_ventas as 'Subtotal', v.IVA, v.Total_venta as 'Total' FROM ventas v, clientes c, producto p WHERE v.ID_NFacturas = '" + fact + "' LIMIT 1;");
            rs = psExecute.executeQuery();
            while(rs.next()){
             //   txtFactura.setText(rs.getString("ID"));
                //txtCliente.setText(rs.getString("Nombre"));
                //txtProducto.setText("ID: " + rs.getString("ID_Prod") + " Producto: " + rs.getString("Producto"));
              //  Descuento.setText(rs.getString("Cantidad"));
              //  Monto_restante.setText(rs.getString("Subtotal"));
              //  txtIVA.setText(rs.getString("IVA"));
             //   Date.setText(rs.getString("Total"));
            }
            
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblNombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Forma_Pago = new javax.swing.JTextField();
        ID_Pago = new javax.swing.JTextField();
        Descuento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Nombre_Acreedor = new javax.swing.JTextField();
        Monto_Descuento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Codigo_postal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Monto_pago = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Pagos_Acumulados = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Monto_Restante = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ID_Acreedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Entidad_federativa = new javax.swing.JTextField();

        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pagos acreedores");
        setFocusTraversalPolicyProvider(true);
        setInheritsPopupMenu(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(null);

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombre.setText("Pagos Acreedores");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(30, 10, 190, 30);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 370, 130, 30);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 370, 130, 30);

        jLabel1.setText("ID de pago");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 80, 61, 23);

        jLabel2.setText("Forma de pago");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 120, 80, 20);

        jLabel3.setText("Descuento en %");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 80, 30);
        getContentPane().add(Forma_Pago);
        Forma_Pago.setBounds(110, 110, 170, 30);

        ID_Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_PagoActionPerformed(evt);
            }
        });
        getContentPane().add(ID_Pago);
        ID_Pago.setBounds(80, 70, 200, 30);

        Descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescuentoActionPerformed(evt);
            }
        });
        getContentPane().add(Descuento);
        Descuento.setBounds(110, 150, 170, 30);

        jLabel4.setText("Acreedor");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 120, 80, 20);
        getContentPane().add(Nombre_Acreedor);
        Nombre_Acreedor.setBounds(460, 110, 140, 30);
        getContentPane().add(Monto_Descuento);
        Monto_Descuento.setBounds(460, 190, 140, 30);

        jLabel8.setText("Monto de decuento");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 190, 100, 30);
        getContentPane().add(Codigo_postal);
        Codigo_postal.setBounds(110, 190, 170, 30);

        jLabel7.setText("Codigo postal");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 190, 80, 30);

        jLabel5.setText("Pago");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 250, 30, 20);
        getContentPane().add(Monto_pago);
        Monto_pago.setBounds(70, 240, 210, 30);

        jLabel10.setText("Pagos acumulados");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 230, 110, 30);
        getContentPane().add(Pagos_Acumulados);
        Pagos_Acumulados.setBounds(460, 230, 140, 30);

        jLabel9.setText("Restante por pagar");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 290, 100, 20);
        getContentPane().add(Monto_Restante);
        Monto_Restante.setBounds(130, 280, 150, 30);

        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        getContentPane().add(Date);
        Date.setBounds(460, 280, 140, 30);

        jLabel11.setText("Fecha de pagos");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(360, 280, 90, 30);

        ID_Acreedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_AcreedorActionPerformed(evt);
            }
        });
        getContentPane().add(ID_Acreedor);
        ID_Acreedor.setBounds(430, 70, 170, 30);

        jLabel6.setText("ID Acreedor");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 70, 70, 30);

        jLabel12.setText("Entidad federativa");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(360, 160, 100, 20);
        getContentPane().add(Entidad_federativa);
        Entidad_federativa.setBounds(460, 150, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //Para hacer pruebas con la base de datos, deben modificar la conexión que está aquí
        data.setUser("root");
        data.setPassword("1234");
        data.setDatabaseName("siuv");
        data.setServerName("127.0.0.1");

        try
        {
            conexion = data.getConnection();
            psExecute = conexion.prepareStatement("SELECT Nombre, Apellido FROM empleado WHERE ID_Empleado=1");
            rs = psExecute.executeQuery();
            while(rs.next())
            {
                lblNombre.setText("Nombre obtenido de MySQL: " + rs.getString("Nombre") + " " +  rs.getString("Apellido"));
            }

        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ID_PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_PagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_PagoActionPerformed

    private void DescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescuentoActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void ID_AcreedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_AcreedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_AcreedorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Codigo_postal;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Descuento;
    private javax.swing.JTextField Entidad_federativa;
    private javax.swing.JTextField Forma_Pago;
    private javax.swing.JTextField ID_Acreedor;
    private javax.swing.JTextField ID_Pago;
    private javax.swing.JTextField Monto_Descuento;
    private javax.swing.JTextField Monto_Restante;
    private javax.swing.JTextField Monto_pago;
    private javax.swing.JTextField Nombre_Acreedor;
    private javax.swing.JTextField Pagos_Acumulados;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
