/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CPC;

import siuv.reportViewer;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.beans.PropertyVetoException;
import java.util.HashMap;

/**
 *
 * @author lscauv
 */
public class CPCInicio extends javax.swing.JFrame {

    /**
     * Creates new form CPCInicio
     * @param logged_in
     */
    public CPCInicio(boolean logged_in) {
        if (logged_in != true){
            dispose();
        } else {
            initComponents();
            this.setExtendedState(MAXIMIZED_BOTH);
            desktopPane.setBorder(new ImagenFondo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuCuentas = new javax.swing.JMenu();
        cuentasPendientesMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cobrosMenu = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        salirMenu = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        pagosRealizadosMenu = new javax.swing.JMenuItem();
        pagosPendientesMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        reportePagosPeriodoMenu = new javax.swing.JMenuItem();
        menuHerramientas = new javax.swing.JMenu();
        opcionesMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Módulo de cuentas por cobrar");
        setLocationByPlatform(true);

        menuCuentas.setText("Cuentas");

        cuentasPendientesMenu.setText("Cuentas pendientes");
        cuentasPendientesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentasPendientesMenuActionPerformed(evt);
            }
        });
        menuCuentas.add(cuentasPendientesMenu);
        menuCuentas.add(jSeparator1);

        cobrosMenu.setText("Cobros");
        cobrosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrosMenuActionPerformed(evt);
            }
        });
        menuCuentas.add(cobrosMenu);
        menuCuentas.add(jSeparator4);

        salirMenu.setText("Salir");
        salirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuActionPerformed(evt);
            }
        });
        menuCuentas.add(salirMenu);

        menuBar.add(menuCuentas);

        menuReportes.setText("Reportes");

        pagosRealizadosMenu.setText("Pagos realizados");
        pagosRealizadosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagosRealizadosMenuActionPerformed(evt);
            }
        });
        menuReportes.add(pagosRealizadosMenu);

        pagosPendientesMenu.setText("Pagos pendientes");
        pagosPendientesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagosPendientesMenuActionPerformed(evt);
            }
        });
        menuReportes.add(pagosPendientesMenu);
        menuReportes.add(jSeparator2);

        reportePagosPeriodoMenu.setText("Reporte de pagos por período");
        menuReportes.add(reportePagosPeriodoMenu);

        menuBar.add(menuReportes);

        menuHerramientas.setText("Herramientas");

        opcionesMenu.setText("Opciones");
        menuHerramientas.add(opcionesMenu);

        menuBar.add(menuHerramientas);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuentasPendientesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentasPendientesMenuActionPerformed
        // TODO add your handling code here:
        cuentasPendientes cuentas = new cuentasPendientes();
        cuentas.setVisible(true);
        Dimension dim = desktopPane.getSize();
        Dimension winDim = cuentas.getSize();
        cuentas.setLocation((dim.width - winDim.width) / 2, (dim.height - winDim.height) / 2);
        desktopPane.add(cuentas, javax.swing.JLayeredPane.DEFAULT_LAYER);
    }//GEN-LAST:event_cuentasPendientesMenuActionPerformed

    private void cobrosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrosMenuActionPerformed
        // TODO add your handling code here:
        cobroUnico cobro = new cobroUnico();
        cobro.setVisible(true);
        Dimension dim = desktopPane.getSize();
        Dimension winDim = cobro.getSize();
        cobro.setLocation((dim.width - winDim.width) / 2, (dim.height - winDim.height) / 2);
        desktopPane.add(cobro, javax.swing.JLayeredPane.DEFAULT_LAYER);
    }//GEN-LAST:event_cobrosMenuActionPerformed

    private void salirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirMenuActionPerformed

    private void pagosPendientesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagosPendientesMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pagosPendientesMenuActionPerformed

    private void pagosRealizadosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagosRealizadosMenuActionPerformed
        // TODO add your handling code here:
        HashMap param = new HashMap();
        reportViewer reporte = new reportViewer("./reportes/rptAbonosRealizados.jasper", param);
        CPCInicio.desktopPane.add(reporte, new Integer(20));
        reporte.setVisible(true);
        try{
            reporte.setMaximum(true);
        } catch(PropertyVetoException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_pagosRealizadosMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPCInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPCInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPCInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPCInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CPCInicio(true).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cobrosMenu;
    private javax.swing.JMenuItem cuentasPendientesMenu;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCuentas;
    private javax.swing.JMenu menuHerramientas;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem opcionesMenu;
    private javax.swing.JMenuItem pagosPendientesMenu;
    private javax.swing.JMenuItem pagosRealizadosMenu;
    private javax.swing.JMenuItem reportePagosPeriodoMenu;
    private javax.swing.JMenuItem salirMenu;
    // End of variables declaration//GEN-END:variables
}
